### ISSUE TITLE
Metrics are not sending to specific region

### ISSUE THREAD

**Issue by jtran0721** [buildkite/buildkite-agent-metrics#281]
Hi, I would like some help with sending metrics to different region rather than `us-east-1`. I ran this command 

```
docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e AWS_DEFAULT_REGION="ap-southeast-1" --rm bk-agent-metrics -token $token -interval 30s -queue mac:build -backend cloudwatch -cloudwatch-region "ap-southeast-1”
```

I couldn't see metrics in "ap-southeast-1" but they exist in "us-east-1". Do you know why is this happening?

Thank you

**Comment by DrJosh9000** [comment]
Hi @jtran0721, I think you found a bug!

https://github.com/buildkite/buildkite-agent-metrics/blob/7ffd2908b482274286e01b8f9dce899707ee9ff8/main.go#L75-L81

Since you're passing `-cloudwatch-region`, `region != ""`, so the code ends up in the `else`, which overrides it with `us-east-1`. That's pretty clearly wrong, and has been since that code was added!
